[tool.poetry]
name = "py-slides-term"
version = "0.9.0"
description = "A python module for terminology extraction from presentation slides"
authors = ["Yuya Suwa"]
license = "MIT License"
readme = "README.md"
homepage = "https://github.com/kumachan-mis/py-slides-term"
repository = "https://github.com/kumachan-mis/py-slides-term"
keywords = ["terminology extraction", "technical term", "pdf"]

[tool.poetry.dependencies]
python = ">=3.7"
"pdfminer.six" = "^20201018"
spacy = "^3.0.6"

[tool.poetry.dev-dependencies.en_core_web_sm]
url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz"

[tool.poetry.dev-dependencies.ja_core_news_sm]
url = "https://github.com/explosion/spacy-models/releases/download/ja_core_news_sm-3.0.0/ja_core_news_sm-3.0.0.tar.gz"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
black = "^21.5b0"
pep8-naming = "^0.11.1"
flake8-quotes = "^3.2.0"
pre-commit = "^2.9.3"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
