name: GitHub Pages

on:
  workflow_call:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.5

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.8.4

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Build sphinx documentation
        run: make build-docs

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
