name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    if: ${{ !startsWith(github.event.pull_request.title, '[WIP]') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.11]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
             curl -sSL https://install.python-poetry.org | python -
             echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - run: poetry install --no-interaction
      - run: poetry run pytest
